version: '3'
services:
  ui:
    image: fm_ui:latest
    ports:
      - "3000:3000"
  web:
    build: .
    ports:
      - "8080:8080"
    links:
      - db
  db:
    container_name: db_postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: appdb
    ports:
      - "5001:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: